spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:simpledbapp;
    username: sa
    password:
  jackson:
    deserialization.fail-on-unknown-properties: false
